name: pull docker image and push to ali registry

on:
  release:
    types: [created, edited]

jobs:
  handle_image:
    runs-on: ubuntu-latest
    steps:
    
    - name: Log into registry
      env:
        my_ali_registryaddr: registry.cn-shenzhen.aliyuncs.com/action_0/github
      run: |
        echo -n "${{ secrets.registrytoken }}" | docker login --password-stdin --username=${{ secrets.registryuser }} $my_ali_registryaddr
      
    - name: Pull image
      run: |
        IAMGE_NAME=`echo -n $my_registryaddr | sed  -r "s@(^refs/tags/)|(##.*$)@@g"`
        IMAGE_VERSION= `echo -n $my_registryaddr | sed  -r "s@^.*##@@"`
        docker pull "$IAMGE_NAME":"$IMAGE_VERSION"
        docker images
      
    - name: Push image
      run: |
        docker tag "$IAMGE_NAME":"$IMAGE_VERSION" $my_ali_registryaddr:"$IAMGE_NAME"@"$IMAGE_VERSION"
        docker push $my_ali_registryaddr:"$IAMGE_NAME"@"$IMAGE_VERSION"
        echo "==========="
        echo "=[succeed]="
        echo "Run command at your server:"
        echo "docker pull $my_ali_registryaddr:$IAMGE_NAME@$IMAGE_VERSION"
        echo "==========="