name: pull docker image and push to ali registry

on:
  release:
    types: [created]

jobs:
  handle_image:
    runs-on: ubuntu-latest
    steps:
    
    - name: Log into registry
      env:
        my_ali_registryaddr: registry.cn-shenzhen.aliyuncs.com/action_0/github
      run: |
        echo -n "${{ secrets.registrytoken }}" | docker login --password-stdin --username=${{ secrets.registryuser }} $my_ali_registryaddr
      
    - name: Pull image
      run: |
        IMAGE_NAME=`echo -n ${{github.ref}} | sed  -r "s#(^refs/tags/)|(@@.*$)|\s##g"`
        IMAGE_VERSION= `echo -n $my_registryaddr | sed  -r "s#(^.*@@)|\s##g"`
        echo "[Debug]IMAGE_NAME: " $IMAGE_NAME
        echo "[Debug]IMAGE_VERSION: " $IMAGE_VERSION
        docker pull "$IMAGE_NAME":"$IMAGE_VERSION"
        docker images
      
    - name: Push image
      run: |
        docker tag "$IMAGE_NAME":"$IMAGE_VERSION" $my_ali_registryaddr:"$IMAGE_NAME"@@"$IMAGE_VERSION"
        docker push $my_ali_registryaddr:"$IMAGE_NAME"@@"$IMAGE_VERSION"
        echo "==========="
        echo "=[succeed]="
        echo "Run command at your server:"
        echo "docker pull $my_ali_registryaddr:$IMAGE_NAME@@$IMAGE_VERSION"
        echo "==========="